#include "app_main.h"

/* * EXTERNAL HANDLES
 * We import the hardware handles generated by CubeMX so we can use them here.
 */
extern UART_HandleTypeDef huart1;
extern osThreadId_t vTaskIngestionHandle; 

/* * MEMORY ALLOCATIONS
 */
#define RX_BUFFER_SIZE 2048
// Map the buffer to the Non-Cacheable SRAM1 MPU region
uint8_t *rx_ring_buffer = (uint8_t *)0x30000000;

/**
 * @brief Run once before the RTOS scheduler starts
 */
void App_Init(void) 
{
    // Arm the DMA Idle Listener
    HAL_UARTEx_ReceiveToIdle_DMA(&huart1, rx_ring_buffer, RX_BUFFER_SIZE);
}

/**
 * @brief The infinite loop for the Ingestion Task
 */
void App_IngestTask_Loop(void) 
{
    uint16_t old_pos = 0;
    uint16_t new_pos = 0;

    for(;;) 
    {
        // 1. Sleep entirely until the DMA interrupt sets Flag 0x01
        osThreadFlagsWait(0x01, osFlagsWaitAny, osWaitForever);

        // 2. Data arrived! Calculate the DMA write pointer position
        new_pos = RX_BUFFER_SIZE - __HAL_DMA_GET_COUNTER(huart1.hdmarx);

        // Toggle LED to visually confirm data reception
        HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);

        // 3. (Parsing logic will go here)

        old_pos = new_pos;
    }
}

/**
 * @brief The infinite loop for the Transmit Task (Heartbeat test)
 */
void App_TransmitTask_Loop(void) 
{
    volatile uint32_t heartbeat_counter = 0;
    
    for(;;) 
    {
        HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_14);
        heartbeat_counter++;
        osDelay(1000); 
    }
}

/**
 * @brief WEAK CALLBACK OVERRIDE
 * The linker will automatically route the hardware interrupt here instead of main.c!
 */
void HAL_UARTEx_RxEventCallback(UART_HandleTypeDef *huart, uint16_t Size) 
{
    if (huart->Instance == USART1) 
    {
        // Wake up the Ingest Task
        osThreadFlagsSet(vTaskIngestionHandle, 0x01); 
    }
}